site_name: Use case registry

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

nav:
  - "What is this?":
    - "index.md"
  - Clean Architecture:
    - "clean_architecture/index.md"
  - One Use Case, One Workflow:
    - "one_use_case_one_workflow/index.md"
  - Error Handling:
    - "error_handling/index.md"


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


repo_url: https://github.com/Tomperez98/use-case-registry