site_name: Use case registry

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate 

nav:
  - "Home":
    - index.md
    - "One workflow, one usecase": one-workflow-one-usecase.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
